//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.23 at 11:28:20 上午 CST 
//


package com.gdin.report.dto.arrival;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 报文头
 * 
 * <p>Java class for Head complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Head">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="FunctionCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="MessageType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="SenderID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ReceiverID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="SendTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Head", propOrder = {
    "messageID",
    "functionCode",
    "messageType",
    "senderID",
    "receiverID",
    "sendTime",
    "version"
})
public class Head {

    @XmlElement(name = "MessageID", required = true)
    protected Object messageID;
    @XmlElement(name = "FunctionCode", required = true)
    protected Object functionCode;
    @XmlElement(name = "MessageType", required = true)
    protected Object messageType;
    @XmlElement(name = "SenderID", required = true)
    protected Object senderID;
    @XmlElement(name = "ReceiverID", required = true)
    protected Object receiverID;
    @XmlElement(name = "SendTime", required = true)
    protected Object sendTime;
    @XmlElement(name = "Version", required = true)
    protected Object version;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMessageID(Object value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the functionCode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFunctionCode() {
        return functionCode;
    }

    /**
     * Sets the value of the functionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFunctionCode(Object value) {
        this.functionCode = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMessageType(Object value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the senderID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSenderID() {
        return senderID;
    }

    /**
     * Sets the value of the senderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSenderID(Object value) {
        this.senderID = value;
    }

    /**
     * Gets the value of the receiverID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getReceiverID() {
        return receiverID;
    }

    /**
     * Sets the value of the receiverID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReceiverID(Object value) {
        this.receiverID = value;
    }

    /**
     * Gets the value of the sendTime property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSendTime() {
        return sendTime;
    }

    /**
     * Sets the value of the sendTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSendTime(Object value) {
        this.sendTime = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVersion(Object value) {
        this.version = value;
    }

}
