//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 02:58:11 下午 CST 
//


package com.gdin.report.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}FileName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}IcCard"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}BizKey"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileName",
    "icCard",
    "bizKey"
})
@XmlRootElement(name = "AddInfo")
public class AddInfo {

    @XmlElement(name = "FileName", required = true)
    protected FileName fileName;
    @XmlElement(name = "IcCard", required = true)
    protected IcCard icCard;
    @XmlElement(name = "BizKey", required = true)
    protected BizKey bizKey;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link FileName }
     *     
     */
    public FileName getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileName }
     *     
     */
    public void setFileName(FileName value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the icCard property.
     * 
     * @return
     *     possible object is
     *     {@link IcCard }
     *     
     */
    public IcCard getIcCard() {
        return icCard;
    }

    /**
     * Sets the value of the icCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcCard }
     *     
     */
    public void setIcCard(IcCard value) {
        this.icCard = value;
    }

    /**
     * Gets the value of the bizKey property.
     * 
     * @return
     *     possible object is
     *     {@link BizKey }
     *     
     */
    public BizKey getBizKey() {
        return bizKey;
    }

    /**
     * Sets the value of the bizKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BizKey }
     *     
     */
    public void setBizKey(BizKey value) {
        this.bizKey = value;
    }

}
