//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 02:58:11 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.chinaport.gov.cn/dxp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gdin.report.dto;
