//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 02:58:11 下午 CST 
//


package com.gdin.report.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}CopMsgId"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}SenderId"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}ReceiverIds"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}CreatTime"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/dxp}MsgType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "copMsgId",
    "senderId",
    "receiverIds",
    "creatTime",
    "msgType"
})
@XmlRootElement(name = "TransInfo")
public class TransInfo {

    @XmlElement(name = "CopMsgId")
    protected String copMsgId;
    @XmlElement(name = "SenderId", required = true)
    protected String senderId;
    @XmlElement(name = "ReceiverIds", required = true)
    protected ReceiverIds receiverIds;
    @XmlElement(name = "CreatTime", required = true)
    protected XMLGregorianCalendar creatTime;
    @XmlElement(name = "MsgType", required = true)
    protected String msgType;

    /**
     * Gets the value of the copMsgId property.
     * 
     */
    public String getCopMsgId() {
        return copMsgId;
    }

    /**
     * Sets the value of the copMsgId property.
     * 
     */
    public void setCopMsgId(String value) {
        this.copMsgId = value;
    }

    /**
     * Gets the value of the senderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderId(String value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the receiverIds property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverIds }
     *     
     */
    public ReceiverIds getReceiverIds() {
        return receiverIds;
    }

    /**
     * Sets the value of the receiverIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverIds }
     *     
     */
    public void setReceiverIds(ReceiverIds value) {
        this.receiverIds = value;
    }

    /**
     * Gets the value of the creatTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatTime() {
        return creatTime;
    }

    /**
     * Sets the value of the creatTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatTime(XMLGregorianCalendar value) {
        this.creatTime = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

}
