//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 运输工具数据段
 * 
 * <p>Java class for BorderTransportMeans complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BorderTransportMeans">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JourneyID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="TypeCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="FirstArrivalLocationID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ArrivalDateTime" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="DepartureDateTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BorderTransportMeans", propOrder = {
    "journeyID",
    "typeCode",
    "id",
    "name",
    "firstArrivalLocationID",
    "arrivalDateTime",
    "departureDateTime",
        "actualDateTime",
        "completedDateTime",
        "loadingLocation",
        "master",
        "cargofacilitylocation",
        "despatchdatetime",
        "unloadingLocation",
        "unloading",
        "freetext"
})
public class BorderTransportMeans {

    @XmlElement(name = "JourneyID")
    protected   String journeyID;
    @XmlElement(name = "TypeCode")
    protected   String typeCode;
    @XmlElement(name = "ID")
    protected   String id;
    @XmlElement(name = "Name")
    protected   String name;
    @XmlElement(name = "FirstArrivalLocationID")
    protected   String firstArrivalLocationID;
    @XmlElement(name = "ArrivalDateTime")
    protected   String arrivalDateTime;
    @XmlElement(name = "DepartureDateTime")
    protected   String departureDateTime;
    @XmlElement(name = "LoadingLocation")
    protected LoadingLocation loadingLocation;
    @XmlElement(name = "Master")
    protected Captain master;
    @XmlElement(name = "CargoFacilityLocation")
    protected String cargofacilitylocation;
    @XmlElement(name = "DespatchDateTime")
    protected String despatchdatetime;
    @XmlElement(name = "UnloadingLocation")
    protected UnloadingLocation unloadingLocation;
    @XmlElement(name = "Unloading")
    protected Unloading unloading;
    @XmlElement(name = "FreeText")
    protected String freetext;
    @XmlElement(name = "ActualDateTime")
    protected String actualDateTime;
    @XmlElement(name = "CompletedDateTime")
    protected String completedDateTime;



    public LoadingLocation getLoadingLocation() {
        return loadingLocation;
    }

    public void setLoadingLocation(LoadingLocation loadingLocation) {
        this.loadingLocation = loadingLocation;
    }

    public Captain getMaster() {
        return master;
    }

    public void setMaster(Captain master) {
        this.master = master;
    }

    public String getCargofacilitylocation() {
        return cargofacilitylocation;
    }

    public void setCargofacilitylocation(String cargofacilitylocation) {
        this.cargofacilitylocation = cargofacilitylocation;
    }

    public String getDespatchdatetime() {
        return despatchdatetime;
    }

    public void setDespatchdatetime(String despatchdatetime) {
        this.despatchdatetime = despatchdatetime;
    }

    public UnloadingLocation getUnloadingLocation() {
        return unloadingLocation;
    }

    public void setUnloadingLocation(UnloadingLocation unloadingLocation) {
        this.unloadingLocation = unloadingLocation;
    }

    public Unloading getUnloading() {
        return unloading;
    }

    public void setUnloading(Unloading unloading) {
        this.unloading = unloading;
    }

    public String getFreetext() {
        return freetext;
    }

    public void setFreetext(String freetext) {
        this.freetext = freetext;
    }

    public String getActualDateTime() {
        return actualDateTime;
    }

    public void setActualDateTime(String actualDateTime) {
        this.actualDateTime = actualDateTime;
    }

    public String getCompletedDateTime() {
        return completedDateTime;
    }

    public void setCompletedDateTime(String completedDateTime) {
        this.completedDateTime = completedDateTime;
    }




    /**
     * Gets the value of the journeyID property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getJourneyID() {
        return journeyID;
    }

    /**
     * Sets the value of the journeyID property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setJourneyID(  String value) {
        this.journeyID = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setTypeCode(  String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setId(  String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setName(  String value) {
        this.name = value;
    }

    /**
     * Gets the value of the firstArrivalLocationID property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getFirstArrivalLocationID() {
        return firstArrivalLocationID;
    }

    /**
     * Sets the value of the firstArrivalLocationID property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setFirstArrivalLocationID(  String value) {
        this.firstArrivalLocationID = value;
    }

    /**
     * Gets the value of the arrivalDateTime property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getArrivalDateTime() {
        return arrivalDateTime;
    }

    /**
     * Sets the value of the arrivalDateTime property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setArrivalDateTime(  String value) {
        this.arrivalDateTime = value;
    }

    /**
     * Gets the value of the departureDateTime property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getDepartureDateTime() {
        return departureDateTime;
    }

    /**
     * Sets the value of the departureDateTime property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setDepartureDateTime(  String value) {
        this.departureDateTime = value;
    }

}
