//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 12:01:44 下午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 变更集装箱（器）数据段
 * 
 * <p>Java class for ChangeTransportEquipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeTransportEquipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImportTransportEquipment" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}EquipmentIdentification"/>
 *         &lt;element name="ExportTransportEquipment" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}EquipmentIdentification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeTransportEquipment", propOrder = {
    "importTransportEquipment",
    "exportTransportEquipment"
})
public class ChangeTransportEquipment {

    @XmlElement(name = "ImportTransportEquipment")
    protected EquipmentIdentification importTransportEquipment;
    @XmlElement(name = "ExportTransportEquipment")
    protected EquipmentIdentification exportTransportEquipment;

    /**
     * Gets the value of the importTransportEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentIdentification }
     *     
     */
    public EquipmentIdentification getImportTransportEquipment() {
        return importTransportEquipment;
    }

    /**
     * Sets the value of the importTransportEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentIdentification }
     *     
     */
    public void setImportTransportEquipment(EquipmentIdentification value) {
        this.importTransportEquipment = value;
    }

    /**
     * Gets the value of the exportTransportEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentIdentification }
     *     
     */
    public EquipmentIdentification getExportTransportEquipment() {
        return exportTransportEquipment;
    }

    /**
     * Sets the value of the exportTransportEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentIdentification }
     *     
     */
    public void setExportTransportEquipment(EquipmentIdentification value) {
        this.exportTransportEquipment = value;
    }

}
