//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 08:46:12 上午 CST 
//


package com.gdin.report.dto.exp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 变更后提（运）单信息
 * 
 * <p>Java class for ChangeConsignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeConsignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransportContractDocument" type="{urn:Declaration:datamodel:standard:CN:MT8103:1}TransportContractDocument"/>
 *         &lt;element name="AssociatedTransportDocument" type="{urn:Declaration:datamodel:standard:CN:MT8103:1}AssociatedTransportDocument" minOccurs="0"/>
 *         &lt;element name="TransportEquipment" type="{urn:Declaration:datamodel:standard:CN:MT8103:1}TransportEquipment" maxOccurs="9999" minOccurs="0"/>
 *         &lt;element name="ConsignmentItem" type="{urn:Declaration:datamodel:standard:CN:MT8103:1}ConsignmentItem" maxOccurs="999" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeConsignment", propOrder = {
    "transportContractDocument",
    "associatedTransportDocument",
    "transportEquipment",
    "consignmentItem"
})
public class ChangeConsignment {

    @XmlElement(name = "TransportContractDocument")
    protected TransportContractDocument transportContractDocument;
    @XmlElement(name = "AssociatedTransportDocument")
    protected AssociatedTransportDocument associatedTransportDocument;
    @XmlElement(name = "TransportEquipment")
    protected List<TransportEquipment> transportEquipment;
    @XmlElement(name = "ConsignmentItem")
    protected List<ConsignmentItem> consignmentItem;

    /**
     * Gets the value of the transportContractDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TransportContractDocument }
     *     
     */
    public TransportContractDocument getTransportContractDocument() {
        return transportContractDocument;
    }

    /**
     * Sets the value of the transportContractDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportContractDocument }
     *     
     */
    public void setTransportContractDocument(TransportContractDocument value) {
        this.transportContractDocument = value;
    }

    /**
     * Gets the value of the associatedTransportDocument property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedTransportDocument }
     *     
     */
    public AssociatedTransportDocument getAssociatedTransportDocument() {
        return associatedTransportDocument;
    }

    /**
     * Sets the value of the associatedTransportDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedTransportDocument }
     *     
     */
    public void setAssociatedTransportDocument(AssociatedTransportDocument value) {
        this.associatedTransportDocument = value;
    }

    /**
     * Gets the value of the transportEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportEquipment }
     * 
     * 
     */
    public List<TransportEquipment> getTransportEquipment() {
        if (transportEquipment == null) {
            transportEquipment = new ArrayList<TransportEquipment>();
        }
        return this.transportEquipment;
    }

    /**
     * Gets the value of the consignmentItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consignmentItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsignmentItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsignmentItem }
     * 
     * 
     */
    public List<ConsignmentItem> getConsignmentItem() {
        if (consignmentItem == null) {
            consignmentItem = new ArrayList<ConsignmentItem>();
        }
        return this.consignmentItem;
    }

}
