//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.23 at 07:34:53 下午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 改靠港数据段
 * 
 * <p>Java class for ChangePortOfArrival complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangePortOfArrival">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JourneyID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="UnloadingLocation" type="{urn:Declaration:datamodel:standard:CN:MT8101:1}UnloadingLocation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangePortOfArrival", propOrder = {
    "journeyID",
    "unloadingLocation"
})
public class ChangePortOfArrival {

    @XmlElement(name = "JourneyID")
    protected String journeyID;
    @XmlElement(name = "UnloadingLocation")
    protected UnloadingLocation unloadingLocation;

    /**
     * Gets the value of the journeyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJourneyID() {
        return journeyID;
    }

    /**
     * Sets the value of the journeyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJourneyID(String value) {
        this.journeyID = value;
    }

    /**
     * Gets the value of the unloadingLocation property.
     * 
     * @return
     *     possible object is
     *     {@link UnloadingLocation }
     *     
     */
    public UnloadingLocation getUnloadingLocation() {
        return unloadingLocation;
    }

    /**
     * Sets the value of the unloadingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnloadingLocation }
     *     
     */
    public void setUnloadingLocation(UnloadingLocation value) {
        this.unloadingLocation = value;
    }

}
