//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//


package com.gdin.report.dto.exp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 商品项信息
 * 
 * <p>Java class for ConsignmentItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsignmentItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SequenceNumeric" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ConsignmentItemPackaging" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}ConsignmentItemPackaging"/>
 *         &lt;element name="Commodity" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}Commodity"/>
 *         &lt;element name="AdditionalInformation" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}AdditionalInformation" minOccurs="0"/>
 *         &lt;element name="GoodsMeasure" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}GoodsMeasure"/>
 *         &lt;element name="EquipmentIdentification" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}EquipmentIdentification" maxOccurs="9999" minOccurs="0"/>
 *         &lt;element name="CustomsProcedure" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}CustomsProcedure" minOccurs="0"/>
 *         &lt;element name="UCR" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}UCR" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="Origin" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}Origin" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsignmentItem", propOrder = {
    "sequenceNumeric",
    "consignmentItemPackaging",
    "commodity",
    "additionalInformation",
    "goodsMeasure",
    "equipmentIdentification",
    "customsProcedure",
    "ucr",
    "origin"
})
public class ConsignmentItem {

    @XmlElement(name = "SequenceNumeric", required = true)
    protected String sequenceNumeric;
    @XmlElement(name = "ConsignmentItemPackaging", required = true)
    protected ConsignmentItemPackaging consignmentItemPackaging;
    @XmlElement(name = "Commodity", required = true)
    protected Commodity commodity;
    @XmlElement(name = "AdditionalInformation")
    protected AdditionalInformation additionalInformation;
    @XmlElement(name = "GoodsMeasure", required = true)
    protected GoodsMeasure goodsMeasure;
    @XmlElement(name = "EquipmentIdentification", required = true)
    protected List<EquipmentIdentification> equipmentIdentification;
    @XmlElement(name = "CustomsProcedure")
    protected CustomsProcedure customsProcedure;
    @XmlElement(name = "UCR", required = true)
    protected List<UCR> ucr;
    @XmlElement(name = "Origin")
    protected Origin origin;

    /**
     * Gets the value of the sequenceNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public String getSequenceNumeric() {
        return sequenceNumeric;
    }

    /**
     * Sets the value of the sequenceNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSequenceNumeric(String value) {
        this.sequenceNumeric = value;
    }

    /**
     * Gets the value of the consignmentItemPackaging property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignmentItemPackaging }
     *     
     */
    public ConsignmentItemPackaging getConsignmentItemPackaging() {
        return consignmentItemPackaging;
    }

    /**
     * Sets the value of the consignmentItemPackaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignmentItemPackaging }
     *     
     */
    public void setConsignmentItemPackaging(ConsignmentItemPackaging value) {
        this.consignmentItemPackaging = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link Commodity }
     *     
     */
    public Commodity getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commodity }
     *     
     */
    public void setCommodity(Commodity value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInformation }
     *     
     */
    public AdditionalInformation getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInformation }
     *     
     */
    public void setAdditionalInformation(AdditionalInformation value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the goodsMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsMeasure }
     *     
     */
    public GoodsMeasure getGoodsMeasure() {
        return goodsMeasure;
    }

    /**
     * Sets the value of the goodsMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsMeasure }
     *     
     */
    public void setGoodsMeasure(GoodsMeasure value) {
        this.goodsMeasure = value;
    }

    /**
     * Gets the value of the equipmentIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentIdentification }
     * 
     * 
     */
    public List<EquipmentIdentification> getEquipmentIdentification() {
        if (equipmentIdentification == null) {
            equipmentIdentification = new ArrayList<EquipmentIdentification>();
        }
        return this.equipmentIdentification;
    }

    /**
     * Gets the value of the customsProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link CustomsProcedure }
     *     
     */
    public CustomsProcedure getCustomsProcedure() {
        return customsProcedure;
    }

    /**
     * Sets the value of the customsProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomsProcedure }
     *     
     */
    public void setCustomsProcedure(CustomsProcedure value) {
        this.customsProcedure = value;
    }

    /**
     * Gets the value of the ucr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ucr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUCR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UCR }
     * 
     * 
     */
    public List<UCR> getUCR() {
        if (ucr == null) {
            ucr = new ArrayList<UCR>();
        }
        return this.ucr;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Origin }
     *     
     */
    public Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origin }
     *     
     */
    public void setOrigin(Origin value) {
        this.origin = value;
    }

}
