//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 收货人地址信息
 * 
 * <p>Java class for ConsigneeAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsigneeAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CityName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CountrySubEntityID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CountrySubEntityName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="PostcodeID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsigneeAddress", propOrder = {
    "line",
    "cityName",
    "countrySubEntityID",
    "countrySubEntityName",
    "postcodeID",
    "countryCode"
})
public class ConsigneeAddress {

    @XmlElement(name = "Line")
    protected   String line;
    @XmlElement(name = "CityName")
    protected   String cityName;
    @XmlElement(name = "CountrySubEntityID")
    protected   String countrySubEntityID;
    @XmlElement(name = "CountrySubEntityName")
    protected   String countrySubEntityName;
    @XmlElement(name = "PostcodeID")
    protected   String postcodeID;
    @XmlElement(name = "CountryCode")
    protected   String countryCode;

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setLine(  String value) {
        this.line = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setCityName(  String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the countrySubEntityID property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getCountrySubEntityID() {
        return countrySubEntityID;
    }

    /**
     * Sets the value of the countrySubEntityID property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setCountrySubEntityID(  String value) {
        this.countrySubEntityID = value;
    }

    /**
     * Gets the value of the countrySubEntityName property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getCountrySubEntityName() {
        return countrySubEntityName;
    }

    /**
     * Sets the value of the countrySubEntityName property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setCountrySubEntityName(  String value) {
        this.countrySubEntityName = value;
    }

    /**
     * Gets the value of the postcodeID property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getPostcodeID() {
        return postcodeID;
    }

    /**
     * Sets the value of the postcodeID property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setPostcodeID(  String value) {
        this.postcodeID = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setCountryCode(  String value) {
        this.countryCode = value;
    }

}
