//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 12:01:44 下午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 进口提（运）单信息
 * 
 * <p>Java class for ImportConsignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportConsignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransportContractDocument" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}TransportContractDocument"/>
 *         &lt;element name="AssociatedTransportDocument" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}AssociatedTransportDocument" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="LoadingLocation" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}LoadingLocation" minOccurs="0"/>
 *         &lt;element name="ConsignmentPackaging" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}ConsignmentPackaging" minOccurs="0"/>
 *         &lt;element name="TotalGrossMassMeasure" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ConsignmentItem" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}ConsignmentItem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportConsignment", propOrder = {
    "transportContractDocument",
    "loadingLocation",
    "consignmentPackaging",
    "totalGrossMassMeasure",
    "consignmentItem"
})
public class ImportConsignment {

    @XmlElement(name = "TransportContractDocument")
    protected TransportContractDocument transportContractDocument;
    @XmlElement(name = "LoadingLocation")
    protected LoadingLocation loadingLocation;
    @XmlElement(name = "ConsignmentPackaging")
    protected ConsignmentPackaging consignmentPackaging;
    @XmlElement(name = "TotalGrossMassMeasure")
    protected String totalGrossMassMeasure;
    @XmlElement(name = "ConsignmentItem")
    protected ConsignmentItem consignmentItem;

    /**
     * Gets the value of the transportContractDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TransportContractDocument }
     *     
     */
    public TransportContractDocument getTransportContractDocument() {
        return transportContractDocument;
    }

    /**
     * Sets the value of the transportContractDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportContractDocument }
     *     
     */
    public void setTransportContractDocument(TransportContractDocument value) {
        this.transportContractDocument = value;
    }

    /**
     * Gets the value of the loadingLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LoadingLocation }
     *     
     */
    public LoadingLocation getLoadingLocation() {
        return loadingLocation;
    }

    /**
     * Sets the value of the loadingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadingLocation }
     *     
     */
    public void setLoadingLocation(LoadingLocation value) {
        this.loadingLocation = value;
    }

    /**
     * Gets the value of the consignmentPackaging property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignmentPackaging }
     *     
     */
    public ConsignmentPackaging getConsignmentPackaging() {
        return consignmentPackaging;
    }

    /**
     * Sets the value of the consignmentPackaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignmentPackaging }
     *     
     */
    public void setConsignmentPackaging(ConsignmentPackaging value) {
        this.consignmentPackaging = value;
    }

    /**
     * Gets the value of the totalGrossMassMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public String getTotalGrossMassMeasure() {
        return totalGrossMassMeasure;
    }

    /**
     * Sets the value of the totalGrossMassMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalGrossMassMeasure(String value) {
        this.totalGrossMassMeasure = value;
    }

    /**
     * Gets the value of the consignmentItem property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignmentItem }
     *     
     */
    public ConsignmentItem getConsignmentItem() {
        return consignmentItem;
    }

    /**
     * Sets the value of the consignmentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignmentItem }
     *     
     */
    public void setConsignmentItem(ConsignmentItem value) {
        this.consignmentItem = value;
    }

}
