//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 12:01:44 下午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 原始舱单数据段
 * 
 * <p>Java class for ImportInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RepresentativePerson" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}RepresentativePerson" minOccurs="0"/>
 *         &lt;element name="BorderTransportMeans" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}BorderTransportMeans"/>
 *         &lt;element name="Consignment" type="{urn:Declaration:datamodel:standard:CN:MT8105:1}ImportConsignment"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportInformation", propOrder = {
    "representativePerson",
    "borderTransportMeans",
    "consignment"
})
public class ImportInformation {

    @XmlElement(name = "RepresentativePerson")
    protected RepresentativePerson representativePerson;
    @XmlElement(name = "BorderTransportMeans")
    protected BorderTransportMeans borderTransportMeans;
    @XmlElement(name = "Consignment")
    protected ImportConsignment consignment;

    /**
     * Gets the value of the representativePerson property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentativePerson }
     *     
     */
    public RepresentativePerson getRepresentativePerson() {
        return representativePerson;
    }

    /**
     * Sets the value of the representativePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentativePerson }
     *     
     */
    public void setRepresentativePerson(RepresentativePerson value) {
        this.representativePerson = value;
    }

    /**
     * Gets the value of the borderTransportMeans property.
     * 
     * @return
     *     possible object is
     *     {@link BorderTransportMeans }
     *     
     */
    public BorderTransportMeans getBorderTransportMeans() {
        return borderTransportMeans;
    }

    /**
     * Sets the value of the borderTransportMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link BorderTransportMeans }
     *     
     */
    public void setBorderTransportMeans(BorderTransportMeans value) {
        this.borderTransportMeans = value;
    }

    /**
     * Gets the value of the consignment property.
     * 
     * @return
     *     possible object is
     *     {@link ImportConsignment }
     *     
     */
    public ImportConsignment getConsignment() {
        return consignment;
    }

    /**
     * Sets the value of the consignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportConsignment }
     *     
     */
    public void setConsignment(ImportConsignment value) {
        this.consignment = value;
    }

}
