//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 装货地信息
 * 
 * <p>Java class for LoadingLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadingLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LoadingDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadingLocation", propOrder = {
    "id",
    "loadingDate"
})
public class LoadingLocation {

    @XmlElement(name = "ID")
    protected   String id;
    @XmlElement(name = "LoadingDate")
    protected   String loadingDate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setID(  String value) {
        this.id = value;
    }

    /**
     * Gets the value of the loadingDate property.
     * 
     * @return
     *     possible   String is
     *     {@link   String }
     *     
     */
    public   String getLoadingDate() {
        return loadingDate;
    }

    /**
     * Sets the value of the loadingDate property.
     * 
     * @param value
     *     allowed   String is
     *     {@link   String }
     *     
     */
    public void setLoadingDate(  String value) {
        this.loadingDate = value;
    }

}
