//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//


package com.gdin.report.dto.exp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gdin.report.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Manifest_QNAME = new QName("urn:Declaration:datamodel:standard:CN:MT1101:1", "Manifest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gdin.report.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExitCustomsOffice }
     * 
     */
    public ExitCustomsOffice createExitCustomsOffice() {
        return new ExitCustomsOffice();
    }

    /**
     * Create an instance of {@link ConsignmentItemPackaging }
     * 
     */
    public ConsignmentItemPackaging createConsignmentItemPackaging() {
        return new ConsignmentItemPackaging();
    }

    /**
     * Create an instance of {@link Commodity }
     * 
     */
    public Commodity createCommodity() {
        return new Commodity();
    }

    /**
     * Create an instance of {@link Manifest.Declaration }
     * 
     */
    public Manifest.Declaration createManifestDeclaration() {
        return new Manifest.Declaration();
    }

    /**
     * Create an instance of {@link TransportEquipment }
     * 
     */
    public TransportEquipment createTransportEquipment() {
        return new TransportEquipment();
    }

    /**
     * Create an instance of {@link ConsignorAddress }
     * 
     */
    public ConsignorAddress createConsignorAddress() {
        return new ConsignorAddress();
    }

    /**
     * Create an instance of {@link Carrier }
     * 
     */
    public Carrier createCarrier() {
        return new Carrier();
    }

    /**
     * Create an instance of {@link ConsignmentPackaging }
     * 
     */
    public ConsignmentPackaging createConsignmentPackaging() {
        return new ConsignmentPackaging();
    }

    /**
     * Create an instance of {@link UCR }
     * 
     */
    public UCR createUCR() {
        return new UCR();
    }

    /**
     * Create an instance of {@link CustomsProcedure }
     * 
     */
    public CustomsProcedure createCustomsProcedure() {
        return new CustomsProcedure();
    }

    /**
     * Create an instance of {@link Communication }
     * 
     */
    public Communication createCommunication() {
        return new Communication();
    }

    /**
     * Create an instance of {@link TransportContractDocument }
     * 
     */
    public TransportContractDocument createTransportContractDocument() {
        return new TransportContractDocument();
    }

    /**
     * Create an instance of {@link Deconsolidator }
     * 
     */
    public Deconsolidator createDeconsolidator() {
        return new Deconsolidator();
    }

    /**
     * Create an instance of {@link Consignment }
     * 
     */
    public Consignment createConsignment() {
        return new Consignment();
    }

    /**
     * Create an instance of {@link NotifypartyAddress }
     * 
     */
    public NotifypartyAddress createNotifypartyAddress() {
        return new NotifypartyAddress();
    }

    /**
     * Create an instance of {@link DeliveryDestinationAddress }
     * 
     */
    public DeliveryDestinationAddress createDeliveryDestinationAddress() {
        return new DeliveryDestinationAddress();
    }

    /**
     * Create an instance of {@link FreightPayment }
     * 
     */
    public FreightPayment createFreightPayment() {
        return new FreightPayment();
    }

    /**
     * Create an instance of {@link BorderTransportMeans }
     * 
     */
    public BorderTransportMeans createBorderTransportMeans() {
        return new BorderTransportMeans();
    }

    /**
     * Create an instance of {@link IntermediateCarrier }
     * 
     */
    public IntermediateCarrier createIntermediateCarrier() {
        return new IntermediateCarrier();
    }

    /**
     * Create an instance of {@link UnloadingLocation }
     * 
     */
    public UnloadingLocation createUnloadingLocation() {
        return new UnloadingLocation();
    }

    /**
     * Create an instance of {@link NotifyParty }
     * 
     */
    public NotifyParty createNotifyParty() {
        return new NotifyParty();
    }

    /**
     * Create an instance of {@link RepresentativePerson }
     * 
     */
    public RepresentativePerson createRepresentativePerson() {
        return new RepresentativePerson();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link GoodsMeasure }
     * 
     */
    public GoodsMeasure createGoodsMeasure() {
        return new GoodsMeasure();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link ConsignmentItem }
     * 
     */
    public ConsignmentItem createConsignmentItem() {
        return new ConsignmentItem();
    }

    /**
     * Create an instance of {@link Declaration }
     * 
     */
    public Declaration createDeclaration() {
        return new Declaration();
    }

    /**
     * Create an instance of {@link GoodsReceiptPlace }
     * 
     */
    public GoodsReceiptPlace createGoodsReceiptPlace() {
        return new GoodsReceiptPlace();
    }

    /**
     * Create an instance of {@link ConsigneeAddress }
     * 
     */
    public ConsigneeAddress createConsigneeAddress() {
        return new ConsigneeAddress();
    }

    /**
     * Create an instance of {@link Consignee }
     * 
     */
    public Consignee createConsignee() {
        return new Consignee();
    }

    /**
     * Create an instance of {@link AssociatedTransportDocument }
     * 
     */
    public AssociatedTransportDocument createAssociatedTransportDocument() {
        return new AssociatedTransportDocument();
    }

    /**
     * Create an instance of {@link AdditionalInformation }
     * 
     */
    public AdditionalInformation createAdditionalInformation() {
        return new AdditionalInformation();
    }

    /**
     * Create an instance of {@link TransportEquipment.SealID }
     * 
     */
    public TransportEquipment.SealID createTransportEquipmentSealID() {
        return new TransportEquipment.SealID();
    }

    /**
     * Create an instance of {@link TranshipmentLocation }
     * 
     */
    public TranshipmentLocation createTranshipmentLocation() {
        return new TranshipmentLocation();
    }

    /**
     * Create an instance of {@link Consignor }
     * 
     */
    public Consignor createConsignor() {
        return new Consignor();
    }

    /**
     * Create an instance of {@link EquipmentIdentification }
     * 
     */
    public EquipmentIdentification createEquipmentIdentification() {
        return new EquipmentIdentification();
    }

    /**
     * Create an instance of {@link PreviousCustomsDocument }
     * 
     */
    public PreviousCustomsDocument createPreviousCustomsDocument() {
        return new PreviousCustomsDocument();
    }

    /**
     * Create an instance of {@link Consignment.ValueAmount }
     * 
     */
    public Consignment.ValueAmount createConsignmentValueAmount() {
        return new Consignment.ValueAmount();
    }

    /**
     * Create an instance of {@link Handling }
     * 
     */
    public Handling createHandling() {
        return new Handling();
    }

    /**
     * Create an instance of {@link TransitDestination }
     * 
     */
    public TransitDestination createTransitDestination() {
        return new TransitDestination();
    }

    /**
     * Create an instance of {@link LoadingLocation }
     * 
     */
    public LoadingLocation createLoadingLocation() {
        return new LoadingLocation();
    }

    /**
     * Create an instance of {@link GoodsConsignedPlace }
     * 
     */
    public GoodsConsignedPlace createGoodsConsignedPlace() {
        return new GoodsConsignedPlace();
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createOrigin() {
        return new Origin();
    }

    /**
     * Create an instance of {@link UNDGContact }
     * 
     */
    public UNDGContact createUNDGContact() {
        return new UNDGContact();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Manifest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:Declaration:datamodel:standard:CN:MT1101:1", name = "Manifest")
    public JAXBElement<Manifest> createManifest(Manifest value) {
        return new JAXBElement<Manifest>(_Manifest_QNAME, Manifest.class, null, value);
    }

}
