//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//

//urn:Declaration:datamodel:standard:CN:MT1101:1
@javax.xml.bind.annotation.XmlSchema(namespace = "urn:Declaration:datamodel:standard:CN:MT1101:1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gdin.report.dto.exp;
