//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 09:20:48 上午 CST 
//


package com.gdin.report.dto.exp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 运输合同信息
 * 
 * <p>Java class for TransportContractDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportContractDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ChangeReasonCode" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="ConditionCode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Deconsolidator" type="{urn:Declaration:datamodel:standard:CN:MT1101:1}Deconsolidator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportContractDocument", propOrder = {
    "id",
    "changeReasonCode",
    "conditionCode",
    "deconsolidator"
})
public class TransportContractDocument {

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "ChangeReasonCode")
    protected List<String> changeReasonCode;
    @XmlElement(name = "ConditionCode")
    protected String conditionCode;
    @XmlElement(name = "Deconsolidator")
    protected Deconsolidator deconsolidator;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible String is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed String is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the changeReasonCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeReasonCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeReasonCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<String> getChangeReasonCode() {
        if (changeReasonCode == null) {
            changeReasonCode = new ArrayList<String>();
        }
        return this.changeReasonCode;
    }

    /**
     * Gets the value of the conditionCode property.
     * 
     * @return
     *     possible String is
     *     {@link String }
     *     
     */
    public String getConditionCode() {
        return conditionCode;
    }

    /**
     * Sets the value of the conditionCode property.
     * 
     * @param value
     *     allowed String is
     *     {@link String }
     *     
     */
    public void setConditionCode(String value) {
        this.conditionCode = value;
    }

    /**
     * Gets the value of the deconsolidator property.
     * 
     * @return
     *     possible String is
     *     {@link Deconsolidator }
     *     
     */
    public Deconsolidator getDeconsolidator() {
        return deconsolidator;
    }

    /**
     * Sets the value of the deconsolidator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deconsolidator }
     *     
     */
    public void setDeconsolidator(Deconsolidator value) {
        this.deconsolidator = value;
    }

}
